### PR TITLE
Ensure build script works on VS2019-only machine

### PR DESCRIPTION
**Pull request by xavierdecoster**
Copied the relevant functions from NuGet/NuGet.Client repo.

### CODE REVIEW

**Comment by joelverhagen** [comment]
This works okay on the CI (nuget.visualstudio.com) and release (devdiv.visualstudio.com) agents?

**Comment by xavierdecoster** [comment]
> This works okay on the CI (nuget.visualstudio.com) and release (devdiv.visualstudio.com) agents?

CI for this PR is green (nuget.visualstudio.com). How can I test release agents without releasing this private branch?

**Comment by xavierdecoster** [comment]
[Verified](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2976583&view=results) a [private branch](https://nuget.visualstudio.com/NuGetMicrosoft/_git/NuGetDeployment/commit/1e1aa700f43c7edca704e6f8c2f690ff008a1113?refName=refs%2Fheads%2Fdev-issue307) for `NuGetDeployment` on the default Agent Pool.

Given the other pipelines run on the same Agent Pool, I don't expect any issues with this change.

I also modified the following `build.ps1` files and tested the change locally using commit SHA: `b025102b17519474d1921d0c44aac62d15024df9` (which points to the build files in this very PR).

* ServerCommon (this very PR)
* [NuGet.Jobs](https://github.com/NuGet/NuGet.Jobs/blob/master/build.ps1#L12)
* [Metadata v3 Jobs](https://github.com/NuGet/NuGet.Services.Metadata/blob/master/build.ps1#L12)

Please let me know if I need to perform a specific additional test before merging this PR.

@joelverhagen @ryuyu.

**Comment by xavierdecoster** [comment]
Ping

**Pull request merged**
