### PR TITLE
update markdig version

### PR DESCRIPTION
**Pull request by lyndaidaii**
Upgrade markdig to 0.26.0

Test: 
Functional test + unit test
Also manually tested email publisher, detail page with readme package

### CODE REVIEW

**Comment by joelverhagen** [comment]
This should be based on `dev` branch, right?

**Comment by joelverhagen** [comment]
This should be based on dev branch, right?

**Review by joelverhagen — APPROVED** [review]
Rebase on `dev` then :shipit:

**Comment by lyndaidaii** [comment]
> This should be based on `dev` branch, right?

I don't think we have `dev` branch for serverCommon

**Comment by joelverhagen** [comment]
Hmm pre-coffee moment! I was thinking this was Gallery. Sorry! :shipit:

**Pull request merged**
